language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"


# Command to install dependencies.
install:
  - pip install -r requirements/dev.txt
  - python setup.py install

# Build script (If successfully built - no errors)
script:
  - pytest -s
  - pylint search_engine_parser --exit-zero

after_success:
  - pysearch --version
  - python setup.py --version

jobs:
  include:
    - stage: deploy
      python: 3.7
      deploy:
        provider: pypi
        user: "deven96"
        password: $PYPI_PASSWORD
        on:
          tags: true
        skip_existing: true

before_deploy:
  - sed -i "s/.*__version__.*/__version__ = \"$TRAVIS_TAG\"/g" search_engine_parser/__init__.py

after_deploy:
  - ./scripts/post_deploy_test.sh
  # - ./scripts/docs.sh

notifications:
# slack channel notification
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y
